### ISSUE TITLE
Your book Building Crossing Platform apps - Chapter 5 

### ISSUE THREAD

**Issue by edxxgardo** [aaronksaunders/ci.alloy.adapter.two#6]
Hello Aaaron,

I'm following your book which I find very cool, but I got stuck in Chapter 5. Could you please help if I put the question here? 
Thans a bunch,

Dario

**Comment by aaronksaunders** [comment]
@edxxgardo if the issue is specific to the book, I would be more than happy to help. All I ask in return is that you take the time to leave some feedback on the amazon website. thx

**Comment by edxxgardo** [comment]
Thanks in advance Aaron,
In reality, there are several issues. Let's start with this starting the Chapter 6. The one from Chapter 5 was fixed already.

commentRow.js:
At the beginning of the file you has to be written

if (user.photo && user.photo.urls) {
    $.avatar.image = user.photo.urls.square_75 ||
  user.photo.urls.thumb_100 || user.photo.urls.original;
}

But, I get an error saying that user.photo is wrong. In fact, If I check the model I get back from comment.save(params, { ...
in 
comment.js 

I get see this:
[INFO] :   {"id":"54f8986c54add893dd336e61","content":"first comment","created_at":"2015-03-05T17:54:52+0000","updated_at":"2015-03-05T17:54:52+0000","user_id":"54f2d3a8de9cf38e181be5e8","reviewed_object":{"type":"Photo","id":"54f4cc4e2ed88cabe309fcd4"},"custom_fields":{}}

And there is not user_id, first_name, last_name  either.

Hope to be clear. Otherwise let me know
Thanks for the help.
Dario

**Comment by aaronksaunders** [comment]
please post the issue in the proper github repo, this repo has nothing to do with the book. Me responding here does not really help others.
